from pydantic import BaseModel, Field
from typing import Optional
from datetime import datetime


# -----------------------------
# 🟢 CREATE (qr_id auto-generated by DB)
# -----------------------------
class QRCreate(BaseModel):
    qr_name: str
    lat: Optional[float] = None
    lon: Optional[float] = None
    status: Optional[str] = "active"
    factory_code: Optional[str] = None

    # ✅ Make optional; default handled in backend
    waiting_time: Optional[int] = Field(
        default=None,
        ge=0,
        description="Waiting time in seconds"
    )


# -----------------------------
# 🟡 UPDATE (qr_id NOT editable)
# -----------------------------
class QRUpdate(BaseModel):
    qr_name: Optional[str] = None
    lat: Optional[float] = None
    lon: Optional[float] = None
    status: Optional[str] = None
    factory_code: Optional[str] = None

    # ✅ Optional for update
    waiting_time: Optional[int] = Field(
        default=None,
        ge=0,
        description="Waiting time in seconds"
    )


# -----------------------------
# 🔵 RESPONSE MODEL
# -----------------------------
class QROut(BaseModel):
    qr_id: int
    qr_name: str
    lat: Optional[float] = None
    lon: Optional[float] = None
    status: Optional[str] = None
    factory_code: Optional[str] = None
    waiting_time: int
    created_at: datetime

    class Config:
        from_attributes = True  # for SQLAlchemy compatibility
