'use client'

import { ActivityBadge } from './ActivityBadge'
import type { Activity } from './types'

interface ActivityDetailsProps {
  activity: Activity | null
  onClose: () => void
  isOpen: boolean
}

export function ActivityDetails({
  activity,
  onClose,
  isOpen,
}: ActivityDetailsProps) {
  if (!activity || !isOpen) return null

  const formatDate = (timestamp?: string) => {
    if (!timestamp) return '-'
    const date = new Date(timestamp)
    return date.toLocaleString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
    })
  }

  const getStatusColor = (status: Activity['status']) => {
    switch (status) {
      case 'Success':
        return 'bg-green-100 text-green-800'
      case 'Warning':
        return 'bg-yellow-100 text-yellow-800'
      case 'Failed':
        return 'bg-red-100 text-red-800'
      default:
        return 'bg-gray-100 text-gray-800'
    }
  }

  const renderActivitySpecificDetails = () => {
    switch (activity.type) {
      case 'QR Scan':
        return (
          <div className="space-y-2">
            <Detail label="QR Code ID" value={activity.id} />
            <Detail label="Scan Point" value={activity.scanPointName} />
            <Detail label="Result" value={activity.status} />
          </div>
        )

      case 'Missed Scan':
        return (
          <div className="space-y-2">
            <Detail label="Expected Scan Time" value={formatDate(activity.expectedScanTime)} />
            <Detail label="Miss Duration" value={`${activity.missDuration ?? 0} minutes`} />
            <Detail label="Auto Generated" value={activity.autoGenerated ? 'Yes' : 'No'} />
          </div>
        )

      case 'Issue Reported':
        return (
          <div className="space-y-2">
            <Detail label="Issue Type" value={activity.issueType} />
            <Detail label="Description" value={activity.description} />
            <Detail label="Severity" value={activity.severity} />
          </div>
        )

      case 'Patrol Started':
      case 'Patrol Completed':
        return (
          <div className="space-y-2">
            <Detail label="Patrol Name" value={activity.patrolName} />
            <Detail label="Completed Scan Points" value={`${activity.completedScanPoints ?? 0} / ${activity.totalScanPoints ?? 0}`} />
          </div>
        )

      case 'Emergency Alert':
        return (
          <div className="space-y-2">
            <Detail label="Alert Type" value={activity.alertType} />
            <Detail label="Resolved" value={activity.resolved ? 'Yes' : 'No'} />
          </div>
        )

      default:
        return null
    }
  }

  return (
    <div className="fixed inset-0 z-50 bg-black/40 flex items-center justify-center">
      <div className="bg-white rounded-lg shadow-xl max-w-lg w-full p-6">
        <div className="flex justify-between items-center mb-4">
          <h3 className="text-lg font-semibold">Activity Details</h3>
          <button onClick={onClose} className="text-gray-400 hover:text-gray-600">
            ✕
          </button>
        </div>

        <div className="space-y-4">
          <div className="flex items-center gap-2">
            <ActivityBadge type={activity.type} />
            <span
              className={`px-2 py-0.5 rounded-full text-xs font-semibold ${getStatusColor(
                activity.status
              )}`}
            >
              {activity.status}
            </span>
          </div>

          <div className="border-t pt-4 space-y-2">
            <Detail label="Activity ID" value={activity.id} />
            <Detail label="Timestamp" value={formatDate(activity.timestamp)} />
            <Detail label="Guard" value={`${activity.guardName} (${activity.guardId})`} />
            <Detail label="Route" value={activity.routeName} />
            <Detail
              label="Location"
              value={[activity.building, activity.floor, activity.area].filter(Boolean).join(', ')}
            />
            <Detail label="Source" value={activity.source} />
          </div>

          <div className="border-t pt-4">
            <h4 className="text-sm font-medium text-gray-500 mb-2">
              Activity Specific Details
            </h4>
            {renderActivitySpecificDetails()}
          </div>
        </div>
      </div>
    </div>
  )
}

/* ========= SMALL HELPER ========= */

function Detail({ label, value }: { label: string; value?: string | number }) {
  return (
    <div className="flex justify-between text-sm">
      <span className="text-gray-500 font-medium">{label}:</span>
      <span className="text-gray-900 text-right max-w-xs">
        {value ?? '-'}
      </span>
    </div>
  )
}
