/* ================= ACTIVITY TYPES ================= */

export type ActivityType =
  | 'QR Scan'
  | 'Missed Scan'
  | 'Issue Reported'
  | 'Patrol Started'
  | 'Patrol Completed'
  | 'Manual Check-In'
  | 'Emergency Alert'

export type ActivityStatus = 'Success' | 'Warning' | 'Failed'
export type ActivitySeverity = 'Low' | 'Medium' | 'High'

export type ScanResult = 'Valid' | 'Invalid' | 'Expired'
export type ScanMode = 'Online' | 'Offline'

/* ================= ACTIVITY ================= */

export interface Activity {
  id: string
  type: ActivityType
  timestamp: string

  guardName: string
  guardId: string

  routeName?: string
  location?: string
  building?: string
  floor?: string
  area?: string

  source: string
  status: ActivityStatus

  /* QR / Scan */
  qrCodeId?: string
  scanPointName?: string
  scanResult?: ScanResult
  scanMode?: ScanMode

  /* Issue */
  issueType?: string
  description?: string
  photoAttached?: boolean
  severity?: ActivitySeverity

  /* Patrol */
  patrolName?: string
  startTime?: string
  endTime?: string
  completedScanPoints?: number
  totalScanPoints?: number

  /* Missed Scan */
  expectedScanTime?: string
  missDuration?: number
  autoGenerated?: boolean

  /* Emergency */
  alertType?: string
  triggeredManually?: boolean
  resolved?: boolean
}

/* ================= FILTERS ================= */

export interface ActivityFilterValues {
  dateRange: string
  activityType: ActivityType | 'All'
  guard: string
  route: string
  severity: ActivitySeverity | 'All'
}
